import "server-only";
import { env, isDatabaseConfigured } from "@/lib/env";
import type { SummarySetup } from "../types";
import { AreaSummaryError } from "./errors";
import { getAiSetup } from "@/modules/ai/server/config";

export function getPublicAreaSummarySetup(): SummarySetup {
  if (!env.ENABLE_AREA_SUMMARIES) {
    return { state: "disabled", message: "Area summaries are disabled. An operator must enable ENABLE_AREA_SUMMARIES on the server." };
  }
  if (!isDatabaseConfigured) {
    return { state: "unconfigured", message: "Reviewed summaries need a configured SQLite database." };
  }
  return { state: "ready", message: "Only current human-reviewed summaries are public." };
}

export function getAreaSummarySetup(): SummarySetup {
  const publicSetup = getPublicAreaSummarySetup();
  if (publicSetup.state !== "ready") return publicSetup;
  const ai = getAiSetup();
  if (!ai.ready) {
    return { state: "unconfigured", message: "Area summaries need SQLite and a configured server-only AI provider. No generation is available until setup is complete." };
  }
  return { state: "ready", message: "Generation is admin-triggered and may incur AI usage charges. Nothing is generated by browsing the map." };
}

export function requireAreaSummarySetup() {
  const setup = getAreaSummarySetup();
  if (setup.state !== "ready") throw new AreaSummaryError(setup.state, setup.message, 503);
}
