import "server-only";
import { env, isSupabaseConfigured } from "@/lib/env";
import type { SummarySetup } from "../types";
import { AreaSummaryError } from "./errors";

export function getPublicAreaSummarySetup(): SummarySetup {
  if (!env.ENABLE_AREA_SUMMARIES) {
    return { state: "disabled", message: "Area summaries are disabled. An operator must enable ENABLE_AREA_SUMMARIES on the server." };
  }
  if (!isSupabaseConfigured) {
    return { state: "unconfigured", message: "Reviewed summaries need a configured backend and migration 0004." };
  }
  return { state: "ready", message: "Only current human-reviewed summaries are public." };
}

export function getAreaSummarySetup(): SummarySetup {
  const publicSetup = getPublicAreaSummarySetup();
  if (publicSetup.state !== "ready") return publicSetup;
  if (!env.SUPABASE_SERVICE_ROLE_KEY || !env.OPENAI_API_KEY.trim()) {
    return { state: "unconfigured", message: "Area summaries need Supabase, the service-role key, migration 0004 and a server-only OPENAI_API_KEY. No generation is available until setup is complete." };
  }
  return { state: "ready", message: "Generation is admin-triggered and may incur OpenAI charges. Nothing is generated by browsing the map." };
}

export function requireAreaSummarySetup() {
  const setup = getAreaSummarySetup();
  if (setup.state !== "ready") throw new AreaSummaryError(setup.state, setup.message, 503);
}
